//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AutoParts = new HashSet<AutoPart>();
            this.NowInfoes = new HashSet<NowInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<AutoPart> AutoParts { get; set; }
        public virtual ICollection<NowInfo> NowInfoes { get; set; }
    }
}
